name: Check Dev Release

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.check_repo.outputs.current_version }}
      latest: ${{ steps.check_anaconda.outputs.latest_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current version from repo
        id: check_repo
        run: |           
          # Read the local version from version.json
          CURRENT_VERSION=$(jq -r .dev ab_releases/current.json)
          echo "Current version: $CURRENT_VERSION"
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Get latest version from Anaconda
        id: check_anaconda
        run: |
          # Variables
          ANACONDA_API_URL="https://api.anaconda.org/package/bsteubing/activity-browser-dev"
          LABEL="main"
          
          # Fetch the package information from Anaconda
          PACKAGE_INFO=$(curl -s $ANACONDA_API_URL)

          # Extract the latest version for the specified label
          LATEST_VERSION=$(echo $PACKAGE_INFO | jq -r --arg LABEL "$LABEL" '.files[] | select(.labels[] == $LABEL) | .version' | sort -V | tail -n 1)
          echo "Latest version: $LATEST_VERSION"
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT

  build-dev-windows:
    runs-on: windows-latest
    needs: check-release
    if: ${{ needs.check-release.outputs.current != needs.check-release.outputs.latest }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install current environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ab_releases/dev/windows/win-environment-${{needs.check-release.outputs.current}}.txt
          environment-name: environment
      - name: Update to latest
        run: |
          micromamba install -n environment -c bsteubing -y activity-browser-dev=${{needs.check-release.outputs.latest}}
      - name: List updated environment
        run: |
          echo micromamba env export --explicit -n environment >> ab_releases/dev/windows/win-environment-${{needs.check-release.outputs.latest}}.txt
          git add ab_releases/dev/windows/win-environment-${{needs.check-release.outputs.latest}}
      - name: Create pull request
        run: gh pr create -B main -H main --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
